import Head from 'next/head'
import Warning from '../Components/Warning/Index'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Abrham Muche</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Warning />
      
    </div>
  )
}
