import Head from 'next/head'
import Script from 'next/script'
import Warning from '../Components/Warning/Index'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Abrham Muche</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://cdn.tailwindcss.com"></Script>
    <Warning />
      
    </div>
  )
}
